# Generated by Django 4.1.2 on 2022-10-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='sam@gmail.com', max_length=254, unique=True),
        ),
    ]
