# Generated by Django 4.1.2 on 2022-10-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
