# Generated by Django 4.1.2 on 2022-10-11 15:40

import Petstagram_project.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', validators=[Petstagram_project.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
