# Generated by Django 4.1.2 on 2022-10-21 15:47

import Petstagram_project.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pet_photos/', validators=[Petstagram_project.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
