# Generated by Django 4.1.2 on 2022-10-28 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
    ]
